import { chromium } from 'playwright';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
import type { SDKMessage } from '@anthropic-ai/claude-agent-sdk';
import type { Agent, Room } from '../src/contracts.js';
import { startService } from '../src/server.js';
const dir = await mkdtemp(join(tmpdir(), 'raft-stream-ui-'));
const streams: { emit: (m: SDKMessage) => void; finish: () => void; apiId: string; agentId: string }[] = [];
const service = await startService(resolve('.'), dir, { ANTHROPIC_API_KEY: 'fake-test' }, async (_prompt, options, emit) => {
  const actor = service.scheduler.tokens.get(options.env!.RAFT_RUN_TOKEN!)!;
  if (actor.kind !== 'agent') throw new Error('missing actor');
  await new Promise<void>((finish, reject) => {
    streams.push({ emit, finish, apiId: randomUUID(), agentId: actor.agentId });
    options.abortController!.signal.addEventListener('abort', () => reject(new Error('stopped')), { once: true });
  });
});
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1350, height: 900 } });
const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
const partial = (stream: typeof streams[number], text: string, start = false) => {
  if (start) stream.emit({ type: 'stream_event', parent_tool_use_id: null, event: { type: 'message_start', message: { id: stream.apiId } } } as SDKMessage);
  stream.emit({ type: 'stream_event', parent_tool_use_id: null, event: { type: 'content_block_delta', index: 0, delta: { type: 'text_delta', text } } } as SDKMessage);
};
try {
  const exec = (name: string, args: Record<string, unknown>) => service.store.execute({ kind: 'user' }, { name, args, requestId: randomUUID() });
  const a = exec('agent.create', { name: '技术雷达', role: '整理技术资料' }) as Agent;
  const b = exec('agent.create', { name: '技术教学', role: '拆解技术概念' }) as Agent;
  const room = exec('room.create', { name: '学习群', members: [a.id, b.id] }) as Room;
  exec('agent.stop', { id: a.id });
  await page.goto(service.url);
  await page.locator('.nav-item').filter({ hasText: '技术雷达' }).click();
  await page.getByLabel('输入消息').fill('介绍 Go 并发'); await page.getByLabel('发送消息').click();
  await page.getByRole('status', { name: '技术雷达 正在回复' }).waitFor();
  await page.getByLabel('停止回复').waitFor();
  assert.equal(await page.locator('.typing-dots i').count(), 3);
  assert.equal(await page.locator('.stop-square').count(), 1);
  await page.getByLabel('切换状态栏').click();
  assert.equal(await page.locator('.member-row button').count(), 0);
  await page.getByLabel('收起状态栏').click();
  partial(streams[0]!, '先从 goroutine', true);
  await page.locator('.streaming-bubble').getByText('先从 goroutine', { exact: true }).waitFor();
  partial(streams[0]!, ' 和 channel 开始。');
  await page.locator('.streaming-bubble').getByText('先从 goroutine 和 channel 开始。', { exact: true }).waitFor();
  await page.reload(); await page.locator('.nav-item').filter({ hasText: '技术雷达' }).click();
  await page.locator('.streaming-bubble').getByText('先从 goroutine 和 channel 开始。', { exact: true }).waitFor();
  await page.getByLabel('输入消息').fill('下一条问题'); await page.getByLabel('输入消息').press('Enter');
  assert.equal(await page.getByLabel('输入消息').inputValue(), '下一条问题'); assert.equal(streams.length, 1);
  const out = resolve('.raft/verification'); await mkdir(out, { recursive: true });
  await page.screenshot({ path: join(out, 'chat-streaming.png'), animations: 'disabled' });
  await page.getByLabel('停止回复').click();
  await page.getByLabel('发送消息').waitFor();
  assert.equal(await page.locator('.loading-message').count(), 0);
  await page.locator('.interrupted-note').getByText('已停止').waitFor();
  assert.equal(await page.getByLabel('输入消息').inputValue(), '下一条问题');
  await page.getByLabel('发送消息').click(); await page.getByLabel('停止回复').waitFor();
  partial(streams[1]!, '这是新的回复', true);
  streams[1]!.emit({ type: 'assistant', uuid: randomUUID(), parent_tool_use_id: null, message: { id: streams[1]!.apiId, content: [{ type: 'text', text: '这是新的回复' }] } } as SDKMessage);
  streams[1]!.finish();
  await page.getByLabel('发送消息').waitFor();
  assert.equal(await page.locator('.message-bubble').getByText('这是新的回复', { exact: true }).count(), 1);
  await page.locator('.room-nav').click();
  exec('room.send', { room: room.id, body: '一起讨论并发边界', mentions: [a.id, b.id] });
  await page.getByRole('status', { name: '群成员正在协作' }).waitFor();
  await page.locator('.group-loading').getByText('技术雷达、技术教学', { exact: false }).waitFor();
  assert.equal(await page.locator('.typing-dots').count(), 1);
  assert.equal(await page.locator('.group-loading .avatar').count(), 2);
  assert.equal(await page.locator('.loading-message').count(), 0);
  partial(streams[2]!, '群内正在分析', true); partial(streams[3]!, '我来补充一个例子', true);
  assert.equal(service.scheduler.streamingMessages.size, 0, '未审核的群草稿不公开');
  const actor = [...service.scheduler.tokens.values()].find(x => x.kind === 'agent' && x.channel === room.id)!;
  service.store.execute(actor, { name: 'room.send', args: { room: room.id, body: '显式发送的群消息', mentions: [b.id], basedOn: service.store.state.rooms.find(r => r.id === room.id)!.version }, requestId: randomUUID() });
  await page.locator('.message-bubble').getByText('显式发送的群消息', { exact: true }).waitFor();
  assert.equal(await page.locator('.streaming-bubble').count(), 0);
  await page.screenshot({ path: join(out, 'chat-streaming-group.png'), animations: 'disabled' });
  await page.locator('.nav-item').filter({ hasText: '技术雷达' }).click();
  assert.equal(await page.getByLabel('停止回复').count(), 0, '群运行不占用私聊停止按钮');
  assert.equal(await page.locator('.streaming-bubble').count(), 0, '群增量不进入私聊');
  await page.locator('.room-nav').click();
  exec('agent.stop', { id: a.id }); service.scheduler.stop(a.id);
  await page.waitForFunction(() => document.querySelectorAll('.group-loading .avatar').length === 1);
  assert.equal(await page.locator('.typing-dots').count(), 1);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: join(out, 'chat-shared-inbox-mobile.png'), animations: 'disabled' });
  await page.getByLabel('停止回复').click();
  await page.getByLabel('发送消息').waitFor();
  assert.equal(service.scheduler.active.size, 0);
  assert.equal(service.store.state.drafts.length, 0, '停止群运行不保存普通输出为草稿');
  assert.deepEqual(service.store.state.messages.filter(m => m.channel === room.id && m.sender !== 'user').map(m => m.text), ['显式发送的群消息']);
  const publicReply = page.locator('article.message').filter({ hasText: '显式发送的群消息' });
  await publicReply.getByLabel('提及的成员').getByText('@技术教学', { exact: true }).waitFor();
  await publicReply.getByRole('button', { name: /撤回 .* 的消息/ }).click();
  await page.getByText('消息已撤回 · 用户撤回', { exact: true }).waitFor();
  assert.equal(await page.locator('.message-bubble').getByText('显式发送的群消息', { exact: true }).count(), 0);
  await page.reload(); await page.locator('.room-nav').click();
  await page.getByText('消息已撤回 · 用户撤回', { exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('CHAT_STREAMING_UI_OK: 自动唤醒、三点动画、实时增量、刷新恢复、完整事件去重、私聊停止保留部分内容、群草稿不提前公开、显式发送、再次发送、群聊多成员与会话隔离。');
} finally { await browser.close(); await service.close(); await rm(dir, { recursive: true, force: true }); }
