import { chromium } from 'playwright';
import { mkdtempSync, mkdirSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';
import { startService } from '../src/server.js';
import { seedEvolution, fakeEvolution, cases } from './evolution-fixture.js';
const dir = mkdtempSync(join(tmpdir(), 'raft-evo-ui-'));
const service = await startService(resolve('.'), dir, { ANTHROPIC_API_KEY: 'local-fixture', ANTHROPIC_MODEL: 'fixture-model' }, async () => {}, undefined, undefined, fakeEvolution);
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
try {
  const { published } = await seedEvolution(service);
  await page.goto(service.url);
  await page.getByRole('button', { name: /Evolver/ }).click();
  await page.getByRole('button', { name: '监测系统', exact: true }).click();
  await page.getByRole('button', { name: '执行日志', exact: true }).click();
  await page.locator('.run-card').first().click();
  const panel = page.getByRole('region', { name: 'Skill 自进化' });
  await panel.getByLabel('待改进 Skill').selectOption(published.id);
  await panel.getByLabel('回归 Case', { exact: true }).fill(JSON.stringify(cases, null, 2));
  await panel.getByRole('button', { name: '生成候选并回归', exact: true }).click();
  await panel.getByText('可晋升', { exact: true }).waitFor();
  assert.equal(await panel.locator('.evolution-trial').count(), 4);
  assert.equal(service.skills.catalogView().find(s => s.id === published.id)!.version, published.version);
  await panel.getByText('查看候选修改', { exact: true }).click();
  assert.match(await panel.locator('.evolution-diff').innerText(), /BASELINE/);
  assert.match(await panel.locator('.evolution-diff').innerText(), /CANDIDATE/);
  await panel.locator('.evolution-trial summary').first().click();
  await panel.locator('.evolution-trial').first().getByText('实际产物', { exact: true }).click();
  const output = resolve('.raft/verification'); mkdirSync(output, { recursive: true });
  await panel.locator('.evaluation-heading').scrollIntoViewIfNeeded();
  await page.screenshot({ path: join(output, 'evolution-desktop.png') });
  await panel.getByRole('button', { name: '晋升为正式版本' }).click();
  await panel.getByText('已晋升', { exact: true }).waitFor();
  assert.notEqual(service.skills.catalogView().find(s => s.id === published.id)!.version, published.version);
  await page.setViewportSize({ width: 390, height: 844 });
  await panel.locator('.evaluation-heading').scrollIntoViewIfNeeded();
  assert.ok(await panel.evaluate(el => el.scrollWidth <= el.clientWidth + 1));
  await page.screenshot({ path: join(output, 'evolution-mobile.png') });
  await panel.getByRole('button', { name: '回滚到基线版本' }).click();
  await panel.getByText('已回滚', { exact: true }).waitFor();
  assert.equal(service.skills.catalogView().find(s => s.id === published.id)!.version, published.version);
  assert.deepEqual(errors, []);
  console.log('EVOLUTION_UI_OK: 未通过评测入口、Case 配置、候选差异、新旧产物、晋升、回滚及 390px 布局通过，无付费调用。');
} finally { await browser.close(); await service.close(); rmSync(dir, { recursive: true, force: true }); }
