import { chromium } from 'playwright';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import assert from 'node:assert/strict';
import type { SessionMessage, SDKMessage } from '@anthropic-ai/claude-agent-sdk';
import type { Agent } from '../src/contracts.js';
import { startService } from '../src/server.js';
import { RunObserver } from '../src/trace.js';
const dir = await mkdtemp(join(tmpdir(), 'raft-inspection-ui-'));
const at = new Date().toISOString();
const rows = [
  ...Array.from({ length: 42 }, (_, i) => ({ type: 'user', uuid: `older-${i}`, session_id: 'fixture-session', message: { role: 'user', content: `历史输入 ${i}` }, parent_tool_use_id: null, parent_agent_id: null, timestamp: at })),
  { type: 'user', uuid: 'fixture-input', session_id: 'fixture-session', message: { role: 'user', content: '读取项目说明，梳理模块职责。' }, parent_tool_use_id: null, parent_agent_id: null, timestamp: at },
  { type: 'assistant', uuid: 'fixture-tool', session_id: 'fixture-session', message: { role: 'assistant', model: 'demo-model', content: [{ type: 'text', text: '先阅读说明，再核对模块入口。' }, { type: 'thinking', thinking: '根据文档与文件验证模块职责。' }, { type: 'tool_use', id: 'read-call-001', name: 'Read', input: { file_path: '/workspace/README.md' } }, { type: 'tool_use', id: 'check-call-001', name: 'Bash', input: { command: 'npm run check' } }, { type: 'tool_use', id: 'pending-call-001', name: 'Grep', input: { pattern: 'TODO', path: '/workspace' } }] }, parent_tool_use_id: null, parent_agent_id: null, timestamp: at },
  { type: 'user', uuid: 'fixture-result', session_id: 'fixture-session', message: { role: 'user', content: [{ type: 'tool_result', tool_use_id: 'read-call-001', content: 'RaftAgent：本地多 Agent 协作助手。' }, { type: 'tool_result', tool_use_id: 'check-call-001', is_error: true, content: 'TypeError: missing config\n' + 'Diagnostic detail\n'.repeat(60) }] }, parent_tool_use_id: null, parent_agent_id: null, timestamp: at },
  { type: 'assistant', uuid: 'fixture-answer', session_id: 'fixture-session', message: { role: 'assistant', content: [{ type: 'text', text: '## 模块核验完成\n\n- **SDK** 管理 Agent 会话。\n- **本地服务** 管理任务与消息。\n\n下一步可查看执行日志。' }] }, parent_tool_use_id: null, parent_agent_id: null, timestamp: at },
] as SessionMessage[];
const service = await startService(resolve('.'), dir, {}, async () => {}, async () => rows);
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
try {
  const agent = service.store.execute({ kind: 'user' }, { name: 'agent.create', args: { name: 'Atlas', role: '核对代码事实，记录执行证据。\n'.repeat(60) }, requestId: 'create' }) as Agent;
  service.store.transact(s => { s.sessions!.push({ agentId: agent.id, channel: agent.id, sdkSessionId: 'fixture-session' }); s.messages.push({ id: 'chat-fixture', channel: agent.id, sender: agent.id, text: '## 项目梳理\n\n已核对模块入口，可以在右侧查看每轮记录和执行日志。', mentions: [], at }); });
  service.traces.start({ id: 'run-ui-001', traceId: 'run-ui-001', agentId: agent.id, inputId: 'fixture-input', sessionId: 'fixture-session', contextVersion: 1, channel: agent.id, kind: 'direct', prompt: '读取项目说明，梳理模块职责。', model: 'demo-model', baseUrl: 'https://example.com', startedAt: at, status: 'running', phase: '等待模型响应' });
  const observer = new RunObserver(service.traces, 'run-ui-001', []);
  const skill = service.skills.traceSkill(agent.id, 'raft:tavily-search')!;
  observer.event('skill.load.start', '开始加载 Skill 说明', skill, { toolId: 'skill-probe' });
  observer.event('skill.loaded', 'Skill 说明已加载', skill, { toolId: 'skill-probe' });
  observer.event('run.start', '开始执行');
  observer.message({ type: 'system', subtype: 'init', session_id: 'fixture-session', model: 'demo-model' } as SDKMessage);
  observer.message({ type: 'system', subtype: 'api_retry', attempt: 1, max_retries: 3, error_status: 429, retry_delay_ms: 1000, error: 'rate_limit' } as SDKMessage);
  observer.toolStart('read-call-001', 'Read', { file_path: '/workspace/README.md' });
  observer.toolEnd('read-call-001', 'Read', { content: 'RaftAgent：本地多 Agent 协作助手。' }, false);
  observer.message({ type: 'result', subtype: 'success', is_error: false, result: 'done', duration_ms: 2450, duration_api_ms: 1800, num_turns: 2, total_cost_usd: 0.0012, modelUsage: { 'demo-model': { inputTokens: 840, outputTokens: 160 } } } as unknown as SDKMessage);
  observer.finish('done');
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write'], { origin: new URL(service.url).origin });
  await page.goto(service.url);
  await page.getByRole('button', { name: /Atlas/ }).click();
  const composer = page.getByLabel('输入消息');
  await composer.fill('保留这段未发送的草稿');
  const header = await page.locator('.conversation-heading').boundingBox();
  const chat = await page.locator('.timeline').boundingBox();
  assert.ok(header && header.height < 80, '长职责不应撑高会话顶部');
  assert.ok(chat && chat.height > 650, '主要高度留给聊天');
  assert.equal(await page.locator('main [role=tab]').count(), 0);
  assert.equal(await page.locator('.inspector').count(), 0, '默认保留完整聊天空间');
  await page.getByRole('button', { name: '切换状态栏' }).click();
  assert.equal(await page.locator('.inspector [role=tab]').count(), 0);
  await page.getByText('职责说明', { exact: true }).click();
  assert.ok((await page.locator('.agent-role').innerText()).length > 500);
  await page.getByRole('button', { name: '监测系统', exact: true }).click();
  await page.getByRole('button', { name: '会话详情', exact: true }).click();
  assert.ok(await composer.isVisible());
  assert.equal(await composer.inputValue(), '保留这段未发送的草稿');
  assert.equal(await page.locator('.workspace-front').getAttribute('inert'), '');
  const panel = page.getByRole('region', { name: '会话详情' });
  const output = resolve('.raft/verification'); await mkdir(output, { recursive: true });
  await panel.locator('.history-record').first().waitFor();
  assert.equal(await panel.locator('.history-record').first().getAttribute('data-message-id'), 'fixture-input');
  assert.ok((await panel.locator('.history-record').first().boundingBox())!.height < 85);
  assert.ok((await panel.locator('.history-controls').boundingBox())!.height < 175);
  await page.screenshot({ path: join(output, 'session-dense.png') });
  await panel.getByRole('button', { name: '切换输入段排序' }).click();
  assert.ok((await panel.locator('.history-record').first().getAttribute('data-message-id'))!.startsWith('older-'));
  await panel.getByRole('button', { name: '切换输入段排序' }).click();
  await panel.getByLabel('筛选会话内容').selectOption('failed');
  assert.equal(await panel.locator('.history-record').count(), 1);
  await panel.locator('.history-row-toggle').click();
  await panel.getByRole('button', { name: '定位调用 ↑' }).last().click();
  assert.equal(await panel.getByLabel('筛选会话内容').inputValue(), 'all');
  const toolRow = panel.locator('[data-message-id="fixture-tool"]');
  assert.equal(await toolRow.locator('.history-row-toggle').getAttribute('aria-expanded'), 'true');
  await toolRow.getByRole('button', { name: '复制 ID', exact: true }).click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), 'fixture-tool');
  await toolRow.getByRole('button', { name: '复制 JSON', exact: true }).click();
  assert.equal(JSON.parse(await page.evaluate(() => navigator.clipboard.readText())).id, 'fixture-tool');
  await toolRow.getByText('调用 Bash', { exact: true }).click();
  await page.waitForResponse(r => r.url().includes('/history?') && r.ok());
  assert.equal(await toolRow.locator('details[open]').count(), 1, '轮询保持工具详情展开');
  await toolRow.getByText('本页无唯一对应结果', { exact: true }).waitFor();
  await panel.getByRole('button', { name: '展开本页' }).click();
  await page.getByRole('heading', { name: '模块核验完成' }).waitFor();
  await panel.getByText('调用 Read', { exact: true }).click();
  await panel.getByText('工具返回', { exact: true }).click();
  assert.equal(await panel.locator('.role-tool').count(), 1);
  assert.ok((await panel.locator('.role-tool').innerText()).includes('read-call-001'));
  await panel.getByLabel('搜索本页会话').fill('模块核验完成');
  assert.equal(await panel.locator('.history-record').count(), 1);
  await panel.getByLabel('搜索本页会话').fill('');
  await panel.getByRole('button', { name: '更早记录 ↑' }).click();
  await panel.getByText('历史输入 0', { exact: true }).waitFor();
  await panel.getByRole('button', { name: '回到最新 ↓' }).click();
  await panel.getByRole('button', { name: '展开本页' }).click();
  await panel.getByRole('heading', { name: '模块核验完成' }).waitFor();
  await panel.getByLabel('筛选会话内容').selectOption('tool');
  await panel.getByText('调用 Read', { exact: true }).click();
  await panel.getByText('工具返回', { exact: true }).click();
  await page.screenshot({ path: join(output, 'session-details.png') });
  await panel.getByRole('button', { name: '全部收起' }).click();
  assert.equal(await panel.locator('.history-row-toggle[aria-expanded=true]').count(), 0);
  await panel.getByRole('button', { name: '查看本轮执行 ↗' }).first().click();
  const logs = page.getByRole('region', { name: '执行日志' });
  await logs.getByText('Skill 使用证据（1）', { exact: true }).click();
  await logs.getByText(/仅观察到加载/).waitFor();
  assert.ok(await composer.isVisible());
  assert.equal(await composer.inputValue(), '保留这段未发送的草稿');
  await logs.getByText('API 请求失败，1 秒后重试', { exact: true }).waitFor();
  await logs.getByLabel('筛选日志级别').selectOption('warn');
  assert.equal(await logs.locator('.explorer-row').count(), 1);
  await logs.getByLabel('筛选日志级别').selectOption('all');
  await logs.getByText('运行配置与用量', { exact: true }).click();
  await logs.getByText('API 请求失败，1 秒后重试', { exact: true }).scrollIntoViewIfNeeded();
  await logs.locator('.explorer-row').filter({ has: page.getByText('调用 Read', { exact: true }) }).click();
  await page.screenshot({ path: join(output, 'execution-trace.png') });
  observer.event('diagnostic.test', '增量日志已到达');
  await logs.getByText('增量日志已到达', { exact: true }).waitFor();
  await page.setViewportSize({ width: 850, height: 720 });
  assert.ok(await logs.evaluate(el => el.scrollWidth <= el.clientWidth + 1));
  await page.screenshot({ path: join(output, 'inspection-narrow.png') });
  await page.getByRole('button', { name: '返回工作区', exact: false }).click();
  await page.getByRole('button', { name: '收起状态栏' }).click();
  assert.equal(await page.locator('.inspector').count(), 0);
  assert.ok(await composer.isVisible());
  assert.equal(await composer.inputValue(), '保留这段未发送的草稿');
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.getByLabel('输入消息').fill('排队验证'); await page.getByLabel('发送消息').click();
  await page.getByRole('button', { name: '监测系统', exact: true }).click();
  await page.getByRole('button', { name: '执行日志', exact: true }).click();
  await logs.getByText('1 条排队', { exact: true }).waitFor();
  assert.equal(service.store.state.runs.length, 0);
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.workspace-front').getAttribute('inert'), null);
  await page.reload();
  await page.getByRole('button', { name: /Atlas/ }).click();
  assert.equal(await page.locator('.inspector').count(), 0, '窄窗口默认收起状态栏');
  await page.getByRole('button', { name: '监测系统', exact: true }).click();
  await page.getByRole('button', { name: '会话详情', exact: true }).click();
  await panel.locator('.history-record').first().waitFor();
  assert.ok(await panel.evaluate(el => el.scrollWidth <= el.clientWidth + 1));
  await page.screenshot({ path: join(output, 'session-dense-narrow.png') });
  await panel.getByRole('button', { name: '展开本页' }).click();
  await page.getByRole('heading', { name: '模块核验完成' }).waitFor();
  assert.deepEqual(errors, []);
  console.log('INSPECTION_UI_OK: 紧凑摘要/输入段排序/失败筛选/工具关联定位/批量折叠/刷新保持展开、历史分页/筛选/工具展开/Run 跳转、日志筛选/增量加载/排队状态/窄屏、紧凑顶部、常驻聊天与草稿保留、侧栏收起/展开/键盘切换，无模型调用。');
} finally { await browser.close(); await service.close(); await rm(dir, { recursive: true, force: true }); }
