import { chromium } from 'playwright';
import { mkdtemp, mkdir, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
import { startService } from '../src/server.js';
const dir = await mkdtemp(join(tmpdir(), 'raft-pricing-ui-'));
const service = await startService(resolve('.'), dir, {}, async () => {});
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const page = await browser.newPage({ viewport: { width: 1280, height: 1000 } });
const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
try {
  await page.goto(service.url);
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.locator('#price-input').fill('2');
  await page.locator('#price-output').fill('8');
  assert.ok(await page.locator('#price-cache').isDisabled());
  await page.getByRole('switch', { name: '开启缓存命中计价' }).check();
  await page.locator('#price-cache').fill('0.2');
  await page.getByRole('button', { name: '保存配置', exact: true }).click();
  await page.locator('.settings-success').waitFor();
  await page.getByRole('button', { name: '关闭设置', exact: true }).click();
  await page.getByRole('button', { name: '设置', exact: true }).click();
  await page.locator('#price-input').waitFor();
  assert.equal(await page.locator('#price-input').inputValue(), '2');
  assert.equal(await page.locator('#price-output').inputValue(), '8');
  assert.equal(await page.locator('#price-cache').inputValue(), '0.2');
  assert.ok(await page.getByRole('switch', { name: '开启缓存命中计价' }).isChecked());
  await mkdir(resolve('.raft/verification'), { recursive: true });
  await page.locator('#price-input').scrollIntoViewIfNeeded();
  await page.screenshot({ path: resolve('.raft/verification/model-pricing-desktop.png') });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.locator('.settings-dialog').evaluate(e => e.scrollWidth <= e.clientWidth + 1));
  await page.locator('#price-input').scrollIntoViewIfNeeded();
  await page.screenshot({ path: resolve('.raft/verification/model-pricing-mobile.png') });
  await page.getByRole('switch', { name: '开启缓存命中计价' }).uncheck();
  await page.getByRole('button', { name: '保存配置', exact: true }).click();
  await page.locator('.settings-success').waitFor();
  assert.equal(service.scheduler.pricing()?.cacheHitEnabled, false);
  await page.getByRole('button', { name: '清除价格配置', exact: true }).click();
  await page.getByRole('button', { name: '保存配置', exact: true }).click();
  await page.locator('.settings-success').waitFor();
  assert.equal(service.scheduler.pricing(), undefined);
  assert.deepEqual(errors, []);
  console.log('MODEL_PRICING_UI_OK');
} finally { await browser.close(); await service.close(); await rm(dir, { recursive: true, force: true }); }
