import { chromium } from 'playwright';
import { mkdtemp, rm, mkdir } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import assert from 'node:assert/strict';
import { startService } from '../src/server.js';
import type { Agent } from '../src/contracts.js';
const dir = await mkdtemp(join(tmpdir(), 'raft-monitor-ui-'));
const service = await startService(resolve('.'), dir, {});
const browser = await chromium.launch({ channel: 'chrome', headless: true });
try {
  const exec = (name: string, args: Record<string, unknown>) => service.store.execute({ kind: 'user' }, { name, args, requestId: randomUUID() });
  const a = exec('agent.create', { name: '技术雷达', role: '追踪技术资料' }) as Agent;
  const b = exec('agent.create', { name: '项目简历助手', role: '整理项目经历' }) as Agent;
  exec('room.create', { name: '秋招工作室', members: [a.id, b.id] });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(service.url);
  await page.locator('.room-nav').click();
  await page.getByLabel('输入消息').fill('翻转后仍然保留的草稿');
  await page.getByRole('button', { name: '监测系统', exact: true }).click();
  await page.getByRole('heading', { name: 'Agent 监测', exact: true }).waitFor();
  await page.waitForFunction(() => !document.querySelector('.workspace-flipper')!.getAnimations().length);
  assert.equal(await page.locator('.workspace-front').getAttribute('inert'), '');
  assert.equal(await page.locator('.monitor-agent-card').count(), 2);
  await page.getByRole('button', { name: '会话详情', exact: true }).click();
  await page.getByText('暂无模型会话').first().waitFor({ timeout: 1500 }).catch(() => {});
  await page.getByRole('button', { name: '执行日志', exact: true }).click();
  await page.getByRole('button', { name: '运行概览', exact: true }).click();
  const out = resolve('.raft/verification'); await mkdir(out, { recursive: true });
  await page.screenshot({ path: join(out, 'monitor-desktop.png') });
  await page.getByRole('button', { name: '返回工作区', exact: false }).click();
  await page.waitForFunction(() => !document.querySelector('.workspace-flipper')!.getAnimations().length);
  assert.equal(await page.getByLabel('输入消息').inputValue(), '翻转后仍然保留的草稿');
  await page.getByRole('button', { name: '监测系统', exact: true }).click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForFunction(() => !document.querySelector('.workspace-flipper')!.getAnimations().length);
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: join(out, 'monitor-mobile.png') });
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.workspace-front').getAttribute('inert'), null);
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.getByRole('button', { name: '监测系统', exact: true }).click();
  assert.equal(await page.locator('.workspace-flipper').evaluate(el => getComputedStyle(el).transitionDuration), '0s');
  assert.deepEqual(errors, []);
  console.log('MONITOR_UI_OK');
} finally { await browser.close(); await service.close(); await rm(dir, { recursive: true, force: true }); }
