import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { mkdtempSync, rmSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';
import { Store } from '../src/store.js';
import { sharedInbox } from '../src/shared-inbox.js';
import { nextSceneInput, sceneKey } from '../src/conversation-context.js';
import { controlCommand, sendControl } from '../src/control.js';
import { startService } from '../src/server.js';
import type { Actor, Agent, Room, Message } from '../src/contracts.js';
import type { SDKMessage } from '@anthropic-ai/claude-agent-sdk';
function fixture(t: test.TestContext, persistent = false) {
  const dir = mkdtempSync(join(tmpdir(), 'raft-shared-inbox-'));
  const path = persistent ? join(dir, 'state.sqlite') : ':memory:';
  const store = new Store(path, dir);
  let closed = false;
  const close = () => { if (!closed) { store.close(); closed = true; } };
  t.after(() => { close(); rmSync(dir, { recursive: true, force: true }); });
  const exec = (name: string, args: Record<string, unknown>, actor: Actor = { kind: 'user' }) => store.execute(actor, { name, args, requestId: randomUUID() });
  const a = exec('agent.create', { name: 'A', role: 'test' }) as Agent;
  const b = exec('agent.create', { name: 'B', role: 'test' }) as Agent;
  const room = exec('room.create', { name: 'Shared', members: [a.id, b.id] }) as Room;
  const actor: Actor = { kind: 'agent', agentId: a.id, runId: 'run', channel: room.id };
  store.transact(s => { s.agents[0]!.status = 'running'; s.runs.push({ id: 'run', agentId: a.id, inputId: 'i', status: 'running', channel: room.id, at: 'now' }); });
  return { store, close, dir, path, exec, a, b, room, actor };
}
test('共享 inbox 按版本增量分页，快照不混入后续消息，成员 ack 不修改公共流', t => {
  const { store, exec, room, actor } = fixture(t);
  for (let i = 0; i < 5; i++) exec('room.send', { room: room.id, body: `消息${i}` });
  const page = exec('inbox.list', { afterVersion: 1, limit: 2 }, actor) as ReturnType<typeof sharedInbox>;
  assert.equal(page.version, 5); assert.deepEqual(page.messages.map(m => m.roomVersion), [2, 3]);
  exec('inbox.ack', { ids: page.messages.map(m => m.id) }, actor);
  exec('room.send', { room: room.id, body: '之后的消息' });
  const next = exec('inbox.list', { afterVersion: 1, limit: 2, cursor: page.nextCursor }, actor) as ReturnType<typeof sharedInbox>;
  assert.equal(next.version, 5); assert.equal(next.currentVersion, 6); assert.equal(next.changed, true);
  assert.deepEqual(next.messages.map(m => m.roomVersion), [4, 5]); assert.equal(next.nextCursor, null);
  assert.throws(() => exec('inbox.list', { afterVersion: 2, limit: 2, cursor: page.nextCursor }, actor), /游标/);
  assert.throws(() => exec('inbox.list', { afterVersion: 99 }, actor), /afterVersion/);
  assert.equal(store.state.receipts.length, 0);
});
test('群普通文本禁止自动发布，显式发送版本冲突留草稿，内部结果单独返回', t => {
  const { store, exec, a, b, room, actor } = fixture(t);
  const make = (text: string, basedOn: number): Message => ({ id: randomUUID(), channel: room.id, sender: a.id, text, basedOn, mentions: [], at: new Date().toISOString() });
  exec('room.send', { room: room.id, body: '目标' });
  assert.throws(() => store.transact(s => store.publishReply(s, make('保持沉默', 1))), /显式发布/);
  exec('room.send', { room: room.id, body: '新增贡献', basedOn: 1 }, actor);
  const result = exec('room.send', { room: room.id, body: '过时贡献', basedOn: 1 }, actor) as { status: string };
  assert.equal(result.status, 'held'); assert.equal(store.state.rooms[0]!.version, 2);
  assert.equal(store.state.messages.length, 2); assert.equal(store.state.drafts.length, 1);
  const input = nextSceneInput(store.state, b.id)!;
  assert.equal(input.roomVersion, 2); assert.match(input.text, /新增贡献/);
  store.transact(s => { s.sceneNotices![sceneKey(b.id, room.id)] = input.noticeThrough!; });
  assert.equal(nextSceneInput(store.state, b.id), undefined, '沉默不推进共享版本，不重复唤醒');
  store.transact(s => { s.messages.push({ id: 'private-result', channel: room.id, sender: b.id, text: '内部结果', internalFor: a.id, mentions: [], at: 'now' }); s.receipts.push({ messageId: 'private-result', agentId: a.id, read: false, arrival: ++s.seq }); });
  const inbox = exec('inbox.list', {}, actor) as ReturnType<typeof sharedInbox> & { notifications: Message[] };
  assert.deepEqual(inbox.messages.map(m => m.text), ['目标', '新增贡献']);
  assert.equal(inbox.notifications[0]!.text, '内部结果');
  assert.equal(inbox.version, 2);
});
test('旧群收件记录迁移只保留一份公共消息，私有回执与处理游标保留，重启幂等', t => {
  const { store, close, exec, path, dir, a, b, room } = fixture(t, true);
  exec('room.send', { room: room.id, body: '旧公共消息' });
  const message = store.state.messages[0]!;
  store.transact(s => {
    delete s.sharedInboxVersion; delete s.rooms[0]!.memberSince; delete s.messages[0]!.roomVersion;
    s.receipts.push({ agentId: a.id, messageId: message.id, arrival: message.seq!, read: true }, { agentId: b.id, messageId: message.id, arrival: message.seq!, read: false });
    s.sceneNotices![sceneKey(a.id, room.id)] = message.seq!;
    s.messages.push({ id: 'internal', channel: room.id, sender: b.id, internalFor: a.id, text: '私有通知', mentions: [], at: 'now' });
    s.receipts.push({ agentId: a.id, messageId: 'internal', arrival: ++s.seq, read: false });
  });
  close();
  const reopened = new Store(path, dir);
  const state = structuredClone(reopened.state); reopened.close();
  assert.equal(state.messages.length, 2); assert.equal(state.messages[0]!.roomVersion, 1);
  assert.deepEqual(state.receipts.map(r => r.messageId), ['internal']);
  assert.equal(state.sceneNotices![sceneKey(a.id, room.id)], message.seq);
  assert.deepEqual(nextSceneInput(state, b.id)!.messageIds, [message.id]);
  const again = new Store(path, dir); assert.deepEqual(again.state, state); again.close();
});
test('CLI 接受版本游标；跨成员和跨群查询仍按身份授权', async t => {
  const parsed = await controlCommand(['inbox', 'list', '--room', 'r', '--after-version', '7', '--limit', '10'], async () => '');
  assert.deepEqual(parsed.args, { room: 'r', afterVersion: 7, limit: 10 });
  const { exec, b, actor } = fixture(t);
  const room = exec('room.create', { name: 'hidden', members: [b.id] }) as Room;
  assert.throws(() => exec('inbox.list', { room: room.id }, actor), /权限/);
});
test('群 SDK 普通流与结束结果不发布；CLI 冲突当轮修订，发送重试幂等', async t => {
  const dir = mkdtempSync(join(tmpdir(), 'raft-shared-runtime-')); let calls = 0;
  const service = await startService(resolve('.'), dir, { ANTHROPIC_API_KEY: 'test' }, async (_prompt, options, emit) => {
    const actor = service.scheduler.tokens.get(options.env!.RAFT_RUN_TOKEN!)!;
    if (actor.kind !== 'agent') throw new Error();
    emit({ type: 'stream_event', parent_tool_use_id: null, event: { type: 'message_start', message: { id: 'silent' } } } as SDKMessage);
    emit({ type: 'stream_event', parent_tool_use_id: null, event: { type: 'content_block_delta', index: 0, delta: { type: 'text_delta', text: '无需回复，保持沉默' } } } as SDKMessage);
    assert.equal(service.scheduler.streamingMessages.size, 0);
    const reply = () => emit({ type: 'assistant', uuid: randomUUID(), parent_tool_use_id: null, message: { id: 'silent', content: [{ type: 'text', text: '无需回复，保持沉默' }] } } as SDKMessage);
    reply();
    emit({ type: 'result', subtype: 'success', result: '本轮结束' } as SDKMessage);
    if (++calls > 1) return;
    service.store.execute({ kind: 'user' }, { name: 'room.send', args: { room: actor.channel, body: '新的约束' }, requestId: randomUUID() });
    const held = await sendControl({ name: 'room.send', args: { room: actor.channel, body: '旧版本回复', basedOn: 1 }, requestId: randomUUID() }, options.env!);
    assert.equal(held.ok, true);
    const data = held.data as { status: string; draftId: string; currentVersion: number; changes: { messages: { text: string }[] } };
    assert.equal(data.status, 'held'); assert.equal(data.currentVersion, 2);
    assert.deepEqual(data.changes.messages.map(m => m.text), ['新的约束']);
    const inbox = await sendControl({ name: 'inbox.list', args: {} }, options.env!);
    assert.equal(inbox.ok, true);
    const command = { name: 'draft.resolve', args: { id: data.draftId, action: 'revise', body: '已经核验新约束', basedOn: (inbox.data as { version: number }).version }, requestId: randomUUID() };
    const sent = await sendControl(command, options.env!);
    assert.equal(sent.ok, true); assert.equal((sent.data as { status: string }).status, 'committed');
    assert.deepEqual(await sendControl(command, options.env!), sent);
    reply(); // Completion narration after sending must not become another public message.
  });
  t.after(async () => { await service.close(); rmSync(dir, { recursive: true, force: true }); });
  const exec = (name: string, args: Record<string, unknown>) => service.store.execute({ kind: 'user' }, { name, args, requestId: randomUUID() });
  const a = exec('agent.create', { name: 'A', role: 'test' }) as Agent;
  const room = exec('room.create', { name: 'R', members: [a.id] }) as Room;
  exec('room.send', { room: room.id, body: '开始' });
  for (let i = 0; i < 300 && (!calls || service.scheduler.active.size); i++) await new Promise(r => setTimeout(r, 10));
  assert.equal(service.scheduler.active.size, 0);
  assert.ok(service.store.state.runs.every(r => r.status === 'done'));
  assert.equal(service.store.state.drafts[0]!.status, 'committed');
  assert.deepEqual(service.store.state.messages.filter(m => m.sender === a.id).map(m => m.text), ['已经核验新约束']);
  assert.equal(service.store.state.messages.at(-1)!.roomVersion, 3);
  assert.equal(calls, 2, '沉默说明不触发新的运行');
  assert.equal(service.scheduler.streamingMessages.size, 0);
});
